name: "Install Solana"
description: "Installs Solana CLI tools"
inputs:
  solana_version:
    description: "Solana version to install"
    required: true
    default: "2.1.0"

runs:
  using: "composite"
  steps:
    - name: Cache Solana install
      id: cache-solana
      uses: actions/cache@v3
      with:
        path: ~/.local/share/solana
        key: solana-${{ inputs.solana_version }}

    - name: Install Solana
      if: steps.cache-solana.outputs.cache-hit != 'true'
      shell: bash
      run: |
        sh -c "$(curl -sSfL https://release.anza.xyz/v${{ inputs.solana_version }}/install)"
        echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

    - name: Set PATH
      shell: bash
      run: echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

    - name: Verify installation
      shell: bash
      run: |
        solana --version
        echo "Solana installed successfully"
