version: 2
updates:
  # Update Cargo dependencies (Rust)
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "cargo"
    labels:
      - "dependencies"
      - "rust"
    open-pull-requests-limit: 10

  # Update NPM dependencies for frontend
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "npm"
    labels:
      - "dependencies"
      - "javascript"
    open-pull-requests-limit: 10

  # Keep GitHub Actions up-to-date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "ci-cd"
      - "dependencies"
    open-pull-requests-limit: 5
