[features]
seeds = false
skip-lint = false

[programs.localnet]
amm_core = "21qXErR6qXr41oTd9QLwMeenW6LYZpDAaxdQxKcCpA4v"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[typescript]
out-dir = "target/types"