[features]
seeds = false
skip-lint = false

[programs.localnet]
fluxa_core = "11111111111111111111111111111112"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/devnet.json"

[typescript]
out-dir = "target/types"