[features]
seeds = false
skip-lint = true

[programs.localnet]
fluxa_core = "4i7vUz8hdydUDGqY2AiabhVJSQZvzDRbSB4kcypnjcWp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[typescript]
out-dir = "target/types"